### ISSUE TITLE
[BUG] - Application Crash After scaling.

### ISSUE THREAD

**Issue by VerzatileDev** [VerzatileDevOrg/C_image_processing#9]
**Description**

Occasionally when the application is bigger than the screen and you aim to scale the application, it becomes frozen and can no longer be moved except the close button which remains functional. The issue also removes the curved edges of the application and defaults to the window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the terminal to make a new main.exe
2. Click on the main.exe
3. When the window opens try rescaling it from the edge of the application, making it go a bit off the screen
4. The application crashes and can no longer be moved where nessecary.

**Expected behaviour**
The expectation was to see the application rescaled or been stopped to avoid it from crashing so that it cannot be further downscaled.

**Screenshots**
![image](https://github.com/VerzatileDevOrg/C_image_processing/assets/47317248/18b70334-22b3-4bf6-9d3a-7423e24ceb41)

**Desktop**
 - Device: [Windows 10 Pro]
 - Version [Pull Request 8]

**Comment by Sommos** [comment]
Fixed by disabling resize on the GTK window.
